load("@units-alpine//classes/alpine_pkg.star", "alpine_pkg")

alpine_pkg(
    name = "linux-firmware",
    version = "20241210-r0",
    license = "custom",
    description = "firmware files for linux (Alpine v3.21)",
    runtime_deps = ["linux-firmware-s5p-mfc", "linux-firmware-yamaha", "linux-firmware-yam", "linux-firmware-xe", "linux-firmware-wfx", "linux-firmware-vxge", "linux-firmware-vicam", "linux-firmware-ueagle-atm", "linux-firmware-ttusb-budget", "linux-firmware-tigon", "linux-firmware-ti-keystone", "linux-firmware-ti-connectivity", "linux-firmware-ti", "linux-firmware-tehuti", "linux-firmware-synaptics", "linux-firmware-sxg", "linux-firmware-sun", "linux-firmware-slicoss", "linux-firmware-sb16", "linux-firmware-rtw89", "linux-firmware-rtw88", "linux-firmware-rtlwifi", "linux-firmware-rtl_nic", "linux-firmware-rtl_bt", "linux-firmware-rsi", "linux-firmware-rockchip", "linux-firmware-realtek", "linux-firmware-radeon", "linux-firmware-r128", "linux-firmware-qlogic", "linux-firmware-qed", "linux-firmware-qcom", "linux-firmware-qca", "linux-firmware-powervr", "linux-firmware-ositech", "linux-firmware-nxp", "linux-firmware-nvidia", "linux-firmware-netronome", "linux-firmware-myricom", "linux-firmware-mwlwifi", "linux-firmware-mwl8k", "linux-firmware-mrvl", "linux-firmware-moxa", "linux-firmware-microchip", "linux-firmware-meson", "linux-firmware-mellanox", "linux-firmware-mediatek", "linux-firmware-matrox", "linux-firmware-liquidio", "linux-firmware-libertas", "linux-firmware-korg", "linux-firmware-keyspan_pda", "linux-firmware-keyspan", "linux-firmware-kaweth", "linux-firmware-ixp4xx", "linux-firmware-isci", "linux-firmware-intel", "linux-firmware-inside-secure", "linux-firmware-imx", "linux-firmware-i915", "linux-firmware-go7007", "linux-firmware-ess", "linux-firmware-ene-ub6250", "linux-firmware-emi62", "linux-firmware-emi26", "linux-firmware-edgeport", "linux-firmware-e100", "linux-firmware-dsp56k", "linux-firmware-dpaa2", "linux-firmware-dabusb", "linux-firmware-cypress", "linux-firmware-cxgb4", "linux-firmware-cxgb3", "linux-firmware-cpia2", "linux-firmware-cnm", "linux-firmware-cis", "linux-firmware-cirrus", "linux-firmware-cavium", "linux-firmware-cadence", "linux-firmware-brcm", "linux-firmware-bnx2x", "linux-firmware-bnx2", "linux-firmware-av7110", "linux-firmware-atusb", "linux-firmware-atmel", "linux-firmware-ath9k_htc", "linux-firmware-ath6k", "linux-firmware-ath12k", "linux-firmware-ath11k", "linux-firmware-ath10k", "linux-firmware-arm", "linux-firmware-ar3k", "linux-firmware-amphion", "linux-firmware-amlogic", "linux-firmware-amdtee", "linux-firmware-amdnpu", "linux-firmware-amdgpu", "linux-firmware-amd-ucode", "linux-firmware-amd", "linux-firmware-airoha", "linux-firmware-advansys", "linux-firmware-adaptec", "linux-firmware-acenic", "linux-firmware-3com", "linux-firmware-other"],
    provides = ["linux-firmware-any"],
    apk_checksum = {
        "x86_64": "Q12QqfdqQ0FRf4xoXARM6yhClnKMg=",
        "arm64": "Q1hsttRVU4aOa+FA11Typqq1UjxMw=",
    },
)
